#!/bin/sh
set -e

curl -sL https://deb.nodesource.com/setup_11.x | sudo -E bash -
sudo apt-get install -y nodejs
npm install

wget https://releases.hashicorp.com/terraform/0.12.3/terraform_0.12.3_linux_amd64.zip -O /tmp/terr.zip
unzip /tmp/terr.zip -d /tmp/terraform
mv /tmp/terraform/terraform /usr/local/bin
