#!/bin/sh
set -xe

cd "$(dirname "$0")/.."

has_command() {
	command -v "$1" >/dev/null 2>&1
}

install_brew() {
	brew bundle
}

if has_command brew; then
	install_brew
else
	echo "you don't have any of the available package managers for this project"
	exit 1
fi