#!/bin/sh
set -e

cd "$(dirname $0)/../terraform"

: "${TF_VAR_domain_name:=tyhal.com}"

export TF_VAR_domain_name

terraform init -input=false
terraform plan

echo "You have 10 seconds to cancel deployment"
sleep 10

terraform apply -auto-approve

aws s3 sync build s3://${TF_VAR_domain_name}
