#!/bin/sh
set -e

cd "$(dirname "$0")/../deploy"

: "${TF_VAR_domain_name:=tyhal.com}"

export TF_VAR_domain_name

terraform init -input=false

set +e
terraform plan -detailed-exitcode -out plan
plan="$?"
set -e

case "$plan" in
"0")
	echo "No changes"
	;;
"2")

	echo "You have 30 seconds to cancel deployment"
	sleep 30
	terraform apply plan
	;;
*)
	echo "Failed"
	exit "$plan"
	;;
esac

( cd ..
npm install
npm run build-css
npm run build
)

docker run --rm \
	-e AWS_ACCESS_KEY_ID \
	-e AWS_SECRET_ACCESS_KEY \
	-e AWS_DEFAULT_REGION \
	-v "$(pwd)/..:/project" \
	mesosphere/aws-cli s3 sync build s3://${TF_VAR_domain_name}
