#!/bin/sh
set -e

cd "$(dirname "$0")/../terraform"

: "${TF_VAR_domain_name:=tyhal.com}"

export TF_VAR_domain_name

terraform init -input=false

set +e
terraform plan -detailed-exitcode -out plan
plan="$?"
set -e

case "$plan" in
"0")
	echo "No changes"
	break
	;;
"2")

	echo "You have 10 seconds to cancel deployment"
	sleep 10
	terraform apply plan
	break
	;;
*)
	echo "Failed"
	exit "$plan"
	;;
esac

cd ..

./script/test

docker run --rm \
	-e AWS_ACCESS_KEY_ID \
	-e AWS_SECRET_ACCESS_KEY \
	-e AWS_DEFAULT_REGION \
	-v "$(pwd):/project" \
	mesosphere/aws-cli s3 sync build s3://${TF_VAR_domain_name}
